/**
 * The asset contract (loops/04-generation.md G2) — the discipline of handing generated bytes to
 * 02's store at the right moment.
 *
 * 02 owns where assets live and how they are indexed. This module owns four rules that hold
 * whatever 02 builds:
 *
 *   download on receipt   a response is not "successful" until put() has resolved
 *   verify the body       a zero-byte or text/html body is an error page, not an image
 *   never the URL         the returned link is dying (§3.5); it is provenance, never a reference
 *   never regenerate      hash the inputs and ask the store first
 *
 * Built at G2 rather than after the generator, because the moment image generation works there is
 * a temptation to store the returned URL and move on, and that bug does not surface for days — the
 * deck simply goes blank and nothing in the logs says why.
 *
 * ── Failing closed ────────────────────────────────────────────────────────────────────────────
 * Until 02 calls `setAssetSink`, every entry point here throws. A generation engine that quietly
 * drops bytes when the store is not wired produces a green test run and no assets, which is
 * exactly the failure the reachability audit exists to catch (`loopdesign.md:249`).
 */

import { createHash } from "node:crypto";
import { XaiError, type AssetPutResult, type AssetSink, type GeneratedAssetKind } from "./types";

export const NO_ASSET_SINK_MESSAGE =
  "no asset store is wired; generation is unavailable. 02 calls setAssetSink() once at startup. " +
  "Refusing rather than generating, because bytes with nowhere to land are a spend with nothing " +
  "to show for it.";

let sink: AssetSink | null = null;

/** 02 wires the store in once at startup. Passing null restores the fail-closed default. */
export function setAssetSink(next: AssetSink | null): void {
  sink = next;
}

/** Whether a store is wired. For the setup panel, which must not trigger the refusal to find out. */
export function isAssetSinkWired(): boolean {
  return sink !== null;
}

/**
 * The store, or a refusal.
 *
 * Every entry point below asks for the store **first**, before it downloads anything or touches
 * the network. The first shape tried here was an unwired sentinel whose methods refused, which
 * meant `persistGenerated` downloaded the whole image and only discovered at `put()` that there
 * was nowhere to put it — the test caught it. Failing closed has to mean nothing happened, not
 * that the last step failed.
 */
export function assetSink(): AssetSink {
  if (!sink) throw new XaiError(NO_ASSET_SINK_MESSAGE, "failed_precondition");
  return sink;
}

// ─────────────────────────────────────────────────────────────────── the regeneration cache

export interface AssetInputs {
  model: string;
  prompt?: string;
  params?: Record<string, unknown>;
}

/**
 * Serialise with keys in sorted order at every depth.
 *
 * `JSON.stringify` preserves insertion order, so `{n: 1, model: "x"}` and `{model: "x", n: 1}`
 * would hash differently and the cache would miss on inputs that are identical. A cache that
 * misses on a key reordering is worse than no cache: it looks like it works.
 */
function canonical(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value) ?? "null";
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  const entries = Object.entries(value as Record<string, unknown>)
    .filter(([, v]) => v !== undefined)
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0));
  return `{${entries.map(([k, v]) => `${JSON.stringify(k)}:${canonical(v)}`).join(",")}}`;
}

/**
 * The cache key: model, prompt and parameters, and nothing else.
 *
 * Deliberately not the project or the agent. The same prompt to the same model with the same
 * parameters produces the same image whoever asked for it, and keying on the asker would make the
 * cache miss every time a second agent wants the picture the first one already paid for.
 */
export function inputHash(inputs: AssetInputs): string {
  return createHash("sha256")
    .update(canonical({ model: inputs.model, prompt: inputs.prompt, params: inputs.params ?? {} }))
    .digest("hex");
}

/**
 * Ask the store whether these exact inputs already produced an asset. **Call this before
 * generating, never after.**
 *
 * This is the strongest cost control in the engine — stronger than any budget cap, because it
 * prevents the spend rather than stopping after it. A 60-second workflow asset is about $5.53
 * against about $0.005 for a text turn, so one avoided regeneration is worth a thousand text
 * turns.
 */
export async function findCachedAsset(inputs: AssetInputs): Promise<{ assetId: string } | null> {
  return assetSink().findByInputHash(inputHash(inputs));
}

// ─────────────────────────────────────────────────────────────────── downloading and verifying

/** Fetches media from a returned URL. Replaced in tests; never replaced in production. */
export type MediaDownloader = (url: string) => Promise<Response>;

const REAL_DOWNLOADER: MediaDownloader = (url) => fetch(url);

let downloader: MediaDownloader = REAL_DOWNLOADER;

/**
 * Replace the media download. Tests only.
 *
 * A separate seam from `setXaiTransport`: a media URL is on a CDN or `vidgen.x.ai`, carries no
 * Authorization header, and is not an api.x.ai endpoint. Sending it through the API transport
 * would mean attaching a credential to a request that does not need one.
 */
export function setMediaDownloader(fn: MediaDownloader | null): void {
  downloader = fn ?? REAL_DOWNLOADER;
}

export type MediaFamily = "image" | "video" | "audio";

const FAMILY_PREFIX: Record<MediaFamily, string> = { image: "image/", video: "video/", audio: "audio/" };

/**
 * Read a media response into bytes, refusing anything that is not the media it claims to be.
 *
 * Each check is a distinct real failure of a proxied media API, and each has a different cause:
 * an HTML error page served with a 200 means the proxy answered instead of the origin; a zero-byte
 * body means the origin answered and had nothing; a short body against a declared Content-Length
 * means the connection dropped mid-transfer. Storing any of the three as an image is how a deck
 * ends up full of broken pictures with a green test run behind it.
 */
export async function readVerifiedMedia(
  response: Response,
  expect: MediaFamily,
  source: string,
): Promise<{ bytes: Uint8Array; mimeType: string }> {
  if (!response.ok) {
    throw new XaiError(
      `downloading ${expect} from ${source} failed with HTTP ${response.status}`,
      "bad_response",
      response.status,
    );
  }

  const mimeType = (response.headers.get("content-type") ?? "").split(";")[0].trim().toLowerCase();
  if (!mimeType.startsWith(FAMILY_PREFIX[expect])) {
    throw new XaiError(
      `downloading ${expect} from ${source} returned content-type "${mimeType || "none"}", not ${FAMILY_PREFIX[expect]}*. ` +
        `An error page served with a success status is not a result.`,
      "bad_response",
      response.status,
    );
  }

  const bytes = new Uint8Array(await response.arrayBuffer());
  if (bytes.byteLength === 0) {
    throw new XaiError(`downloading ${expect} from ${source} returned a zero-byte body`, "bad_response", response.status);
  }

  const declared = response.headers.get("content-length");
  if (declared !== null) {
    const expected = Number(declared);
    if (Number.isFinite(expected) && expected !== bytes.byteLength) {
      throw new XaiError(
        `downloading ${expect} from ${source} was truncated: Content-Length declared ${expected} bytes, ` +
          `${bytes.byteLength} arrived`,
        "bad_response",
        response.status,
      );
    }
  }

  return { bytes, mimeType };
}

// ─────────────────────────────────────────────────────────────────── persisting

/**
 * What a generation response gave us. Exactly one of the three is set.
 *
 * `b64` is the safer shape for a single image because it sidesteps the expiring URL entirely
 * (§5.1); `url` is unavoidable for batches and for video, and is downloaded here, at once.
 */
export interface GeneratedPayload {
  url?: string;
  b64?: string;
  bytes?: Uint8Array;
  /** Used only when the payload is `b64` or `bytes`; a download's own header wins over it. */
  mimeType?: string;
}

export interface PersistArgs {
  payload: GeneratedPayload;
  /** The asset type 02 files this under. */
  kind: GeneratedAssetKind;
  /** The content-type family the body must belong to. */
  expect: MediaFamily;
  projectId: string;
  agentId: string;
  /** Only when 03's caller supplies it. Never inferred from a project id (§1.3). */
  designDocId?: string;
  sourceModel: string;
  sourcePrompt?: string;
  params: Record<string, unknown>;
  requestId?: string;
  costEventId?: string;
}

/**
 * Turn a generation response into a stored asset, and report success only once it is stored.
 *
 * Returns 02's reference and nothing else. In particular it does not return the source URL, so a
 * caller cannot accidentally hold on to the dying link — the only way to reach these bytes
 * afterwards is through the asset id.
 */
/**
 * Turn a generation response into verified bytes — download if it is a URL, decode if it is base64,
 * and refuse anything that is not the media it claims to be.
 *
 * Split out of `persistGenerated` so that a caller which files bytes onto an **existing**
 * deliverable can still go through the four rules at the top of this file. `AssetSink.put` always
 * creates a new asset, so `persistGenerated` is the wrong shape for "add a picture to the document
 * this agent is already writing" — but the verification is the same verification, and a second copy
 * of it in another module would be a second chance to forget the zero-byte check.
 *
 * It does not touch the store, so it does **not** fail closed: bytes returned from here are not yet
 * anywhere. The caller is responsible for reporting success only once they have been persisted.
 */
export async function materialiseGenerated(
  payload: GeneratedPayload,
  expect: MediaFamily,
  what: string,
): Promise<{ bytes: Uint8Array; mimeType: string }> {
  const supplied = [payload.url, payload.b64, payload.bytes].filter((v) => v !== undefined).length;
  if (supplied !== 1) {
    throw new XaiError(
      `a generated ${what} must arrive as exactly one of url, b64 or bytes; ${supplied} were supplied`,
      "invalid_argument",
    );
  }

  if (payload.url !== undefined) {
    const response = await downloader(payload.url);
    return readVerifiedMedia(response, expect, payload.url);
  }

  if (payload.b64 !== undefined) {
    const bytes = Uint8Array.from(Buffer.from(payload.b64, "base64"));
    if (bytes.byteLength === 0) {
      throw new XaiError(`a generated ${what} decoded from base64 to zero bytes`, "bad_response");
    }
    return { bytes, mimeType: payload.mimeType ?? `${FAMILY_PREFIX[expect]}*` };
  }

  const bytes = payload.bytes as Uint8Array;
  if (bytes.byteLength === 0) {
    throw new XaiError(`a generated ${what} was handed over as zero bytes`, "bad_response");
  }
  return { bytes, mimeType: payload.mimeType ?? `${FAMILY_PREFIX[expect]}*` };
}

export async function persistGenerated(args: PersistArgs): Promise<AssetPutResult> {
  const store = assetSink();
  const { payload } = args;

  const { bytes, mimeType } = await materialiseGenerated(payload, args.expect, args.kind);

  // Nothing before this line has reported success, and nothing after it may report success unless
  // this resolves. Settling a job or emitting an asset id ahead of put() loses the asset.
  const stored = await store.put({
    projectId: args.projectId,
    agentId: args.agentId,
    ...(args.designDocId !== undefined ? { designDocId: args.designDocId } : {}),
    bytes,
    mimeType,
    kind: args.kind,
    sourceModel: args.sourceModel,
    ...(args.sourcePrompt !== undefined ? { sourcePrompt: args.sourcePrompt } : {}),
    params: args.params,
    // Provenance only. Expired by the time anyone reads it, and never the durable reference.
    ...(payload.url !== undefined ? { sourceUrl: payload.url } : {}),
    ...(args.requestId !== undefined ? { requestId: args.requestId } : {}),
    ...(args.costEventId !== undefined ? { costEventId: args.costEventId } : {}),
  });

  return stored;
}
